### ISSUE TITLE
license page still points to escience-academy page

### ISSUE THREAD

**Issue by liekelotte** [esciencecenter-digital-skills/next-workshop-template#105]
should be updated to reflect new domain

**Comment by SarahAlidoost** [comment]
@liekelotte the issue has been fixed in PR #102. Looking at the newest workshop page like [2022-03-22-ds-rpackaging](https://esciencecenter-digital-skills.github.io/2022-03-22-ds-rpackaging/), and [2022-02-14-ds-cr](https://esciencecenter-digital-skills.github.io/2022-02-14-ds-cr/), the license page is correct. I close this issue, but please re-open it if the is still a problem.
